[workspace]
members = [
    "radiate-rust",
    "radiate-examples/min-sum",
    "radiate-examples/string-evolver",
    "radiate-extensions", "radiate-examples/xor-graph", "radiate-examples/knapsack",
]
